language: python

sudo: required

services:
  - docker

addons:
  hosts:
    - ecag-fixml-dev1

before_install:
  - sudo add-apt-repository ppa:qpid/released  --yes
  - sudo apt-get update -q
  - sudo apt-get install -q libsasl2-2 libsasl2-modules libsasl2-modules-db qpid-python qpid-cpp
  - docker pull scholzj/fixml:sim

install:
  - docker run -d -p 35672:5672 -p 35671:5671 scholzj/fixml:sim

script:
   - python run_tests.py